/* Shiva 2.0 — PostgreSQL Backend */
const express=require("express");const cors=require("cors");const crypto=require("crypto");const{Pool}=require("pg");
const app=express(),PORT=process.env.PORT||3000;app.use(cors());app.use(express.json({limit:"2mb"}));
if(!process.env.DATABASE_URL)console.warn("WARNING: DATABASE_URL is not configured.");
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:undefined});
async function query(text,params=[]){return pool.query(text,params)}
async function initializeDatabase(){if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL is not configured.");await query(`
CREATE TABLE IF NOT EXISTS users(user_id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,email TEXT UNIQUE,phone TEXT,display_name TEXT,avatar TEXT,role TEXT NOT NULL DEFAULT 'user',password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(session_id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,token TEXT NOT NULL UNIQUE,device_name TEXT,created_at TIMESTAMPTZ NOT NULL,last_seen TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS chats(chat_id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,mode TEXT NOT NULL DEFAULT 'unified',provider TEXT NOT NULL DEFAULT 'gemini',title TEXT NOT NULL DEFAULT 'New Chat',messages JSONB NOT NULL DEFAULT '[]'::jsonb,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS memories(memory_id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,content TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS projects(project_id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS tasks(task_id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,project_id TEXT REFERENCES projects(project_id) ON DELETE SET NULL,title TEXT NOT NULL,completed BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS reset_tokens(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token);CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);CREATE INDEX IF NOT EXISTS idx_chats_user ON chats(user_id);CREATE INDEX IF NOT EXISTS idx_memories_user ON memories(user_id);CREATE INDEX IF NOT EXISTS idx_projects_user ON projects(user_id);CREATE INDEX IF NOT EXISTS idx_tasks_user ON tasks(user_id);CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_id);
`);console.log("PostgreSQL database initialized.")}
function now(){return new Date().toISOString()}function makeId(p="id"){return`${p}_${crypto.randomBytes(16).toString("hex")}`}function norm(v){return String(v||"").trim()}function normalizeUsername(v){return norm(v).toLowerCase()}function normalizeEmail(v){return norm(v).toLowerCase()}function safeText(v,max=10000){return String(v||"").slice(0,max)}function hashPassword(password,salt=crypto.randomBytes(16).toString("hex")){return{salt,hash:crypto.scryptSync(password,salt,64).toString("hex")}}function verifyPassword(password,h,s){try{const a=Buffer.from(crypto.scryptSync(password,s,64).toString("hex"),"hex"),b=Buffer.from(h,"hex");return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}function generateToken(n=48){return crypto.randomBytes(n).toString("hex")}
function publicUser(u){return u?{user_id:u.user_id,username:u.username,email:u.email||null,phone:u.phone||null,display_name:u.display_name||u.username,avatar:u.avatar||null,role:u.role||"user",created_at:u.created_at,updated_at:u.updated_at}:null}
function publicSession(s){return{session_id:s.session_id,user_id:s.user_id,device_name:s.device_name||"Unknown device",created_at:s.created_at,last_seen:s.last_seen,current:false}}
function validateUsername(v){v=norm(v);if(v.length<3||v.length>20)return"Username must be 3–20 characters.";if(!/^[A-Za-z0-9_@]+$/.test(v))return"Username can contain only letters, numbers, _ and @.";if(["admin","administrator","root","system","official","security"].includes(v.toLowerCase()))return"This username is reserved.";return null}
function validatePassword(v){v=String(v||"");return v.length<5||v.length>32?"Password must be 5–32 characters.":null}function validateEmail(v){if(!v)return null;v=normalizeEmail(v);return v.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)?"Invalid email address.":null}
async function createSession(userId,req){const s={session_id:makeId("sess"),user_id:userId,token:generateToken(),device_name:req.body?.device_name||req.headers["user-agent"]||"Browser Session",created_at:now(),last_seen:now()};await query(`INSERT INTO sessions(session_id,user_id,token,device_name,created_at,last_seen)VALUES($1,$2,$3,$4,$5,$6)`,[s.session_id,s.user_id,s.token,s.device_name,s.created_at,s.last_seen]);return s}
function getToken(req){const a=req.headers.authorization||"";return a.startsWith("Bearer ")?a.slice(7).trim():req.headers["x-session-token"]||null}
async function getAuthenticatedUser(req){const t=getToken(req);if(!t)return null;const r=await query(`SELECT s.session_id,s.user_id,s.token,s.device_name,s.created_at AS session_created_at,s.last_seen,u.* FROM sessions s JOIN users u ON u.user_id=s.user_id WHERE s.token=$1 LIMIT 1`,[t]);if(!r.rows.length)return null;const x=r.rows[0],seen=now();await query(`UPDATE sessions SET last_seen=$1 WHERE session_id=$2`,[seen,x.session_id]);return{user:{user_id:x.user_id,username:x.username,email:x.email,phone:x.phone,display_name:x.display_name,avatar:x.avatar,role:x.role,password_hash:x.password_hash,password_salt:x.password_salt,created_at:x.created_at,updated_at:x.updated_at},session:{session_id:x.session_id,user_id:x.user_id,token:x.token,device_name:x.device_name,created_at:x.session_created_at,last_seen:seen}}}
async function optionalAuthenticate(req,res,next){try{const a=await getAuthenticatedUser(req);req.user=a?.user||null;req.session=a?.session||null;next()}catch(e){console.error("Authentication error:",e);req.user=null;req.session=null;next()}}
async function authenticate(req,res,next){await optionalAuthenticate(req,res,()=>req.user?next():res.status(401).json({success:false,error:"Authentication required for this action."}))}
const SHIVA_IDENTITY=`You are Shiva AI inside Shiva 2.0.\nYou are part of the Shiva 2.0 platform developed and created by SHIVA.\nThe selected AI provider (Gemini or Groq) acts as the underlying engine.\nMaintain helpful, direct and continuous assistance.\nNever disclose backend server secrets, API keys, or password hashes.\nWorkspace rule: use the supplied Shiva Memory, Projects and Tasks as shared workspace context. Unified and Split AI share this workspace context; Split AI only keeps its conversation history/provider-specific chat separate.`;
const PROVIDERS={gemini:{name:"Gemini",model:process.env.SHIVA_GEMINI_MODEL||"gemini-3.6-flash"},groq:{name:"Groq",model:process.env.SHIVA_GROQ_MODEL||"openai/gpt-oss-120b"}},COOLDOWN=new Map();function cooling(p){return(COOLDOWN.get(p)||0)>Date.now()}function cooldown(p){COOLDOWN.set(p,Date.now()+60000)}
function cleanHistory(h){return Array.isArray(h)?h.slice(-30).map(x=>({role:x.role==="assistant"?"assistant":"user",content:safeText(x.content,12000)})).filter(x=>x.content.trim()):[]}
async function callGemini(message,history,context){const key=process.env.GEMINI_API_KEY;if(!key)throw Object.assign(new Error("Gemini API key is not configured."),{status:500,provider:"gemini"});const contents=[...cleanHistory(history).map(x=>({role:x.role==="assistant"?"model":"user",parts:[{text:x.content}]})),{role:"user",parts:[{text:message}]}];const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${PROVIDERS.gemini.model}:generateContent?key=${key}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({systemInstruction:{parts:[{text:`${SHIVA_IDENTITY}\n\n${context}`.trim()}]},contents})}),d=await r.json();if(!r.ok)throw Object.assign(new Error(d?.error?.message||"Gemini request failed."),{status:r.status,provider:"gemini"});const out=d?.candidates?.[0]?.content?.parts?.[0]?.text||"";if(!out.trim())throw new Error("Gemini returned an empty response.");return out}
async function callGroq(message,history,context){const key=process.env.GROQ_API_KEY;if(!key)throw Object.assign(new Error("Groq API key is not configured."),{status:500,provider:"groq"});const messages=[{role:"system",content:`${SHIVA_IDENTITY}\n\n${context}`.trim()},...cleanHistory(history),{role:"user",content:message}];const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model:PROVIDERS.groq.model,messages})}),d=await r.json();if(!r.ok)throw Object.assign(new Error(d?.error?.message||"Groq request failed."),{status:r.status,provider:"groq"});const out=d?.choices?.[0]?.message?.content||"";if(!out.trim())throw new Error("Groq returned an empty response.");return out}
async function routeToAI({provider,message,history,context}){const target=provider==="groq"?"groq":"gemini",order=target==="groq"?["groq","gemini"]:["gemini","groq"],fail=[];for(const p of order){if(cooling(p))continue;try{return{reply:p==="groq"?await callGroq(message,history,context):await callGemini(message,history,context),provider:p,model:PROVIDERS[p].model}}catch(e){if(e.status===429)cooldown(p);fail.push(`${p}: ${e.message}`);console.error(`Provider error [${p}]:`,e.message)}}throw Object.assign(new Error(fail.join(" | ")||"No AI providers available."),{status:503})}
app.get("/api/status",async(req,res)=>{try{const r=await query("SELECT NOW() AS time");res.json({success:true,status:"online",database:"postgresql",database_time:r.rows[0].time,name:"Shiva 2.0 Backend",version:"2.0.0",providers:Object.keys(PROVIDERS)})}catch(e){res.status(503).json({success:false,status:"database_unavailable",error:e.message})}});
app.post("/api/message",optionalAuthenticate,async(req,res)=>{try{const{message,history=[],provider="gemini",mode="unified",project_id=null}=req.body||{};if(!norm(message))return res.status(400).json({success:false,error:"Message cannot be empty."});let context="";if(req.user){const[m,p,t]=await Promise.all([query(`SELECT content FROM memories WHERE user_id=$1 ORDER BY created_at DESC LIMIT 12`,[req.user.user_id]),query(`SELECT project_id,name,description FROM projects WHERE user_id=$1 ORDER BY updated_at DESC LIMIT 20`,[req.user.user_id]),query(`SELECT task_id,title,completed,project_id FROM tasks WHERE user_id=$1 ORDER BY completed ASC,updated_at DESC LIMIT 50`,[req.user.user_id])]);if(m.rows.length)context+="\nShiva Memory:\n"+m.rows.reverse().map(x=>`- ${x.content}`).join("\n");if(p.rows.length)context+="\nProjects:\n"+p.rows.map(x=>`- ${x.name}${x.description?": "+x.description:""}${project_id&&x.project_id===project_id?" [CURRENT PROJECT]":""}`).join("\n");if(t.rows.length)context+="\nTasks:\n"+t.rows.map(x=>`- [${x.completed?"done":"open"}] ${x.title}${x.project_id?` (project: ${p.rows.find(q=>q.project_id===x.project_id)?.name||x.project_id})`:""}`).join("\n")}const ai=await routeToAI({provider,message:norm(message),history,context});res.json({success:true,reply:ai.reply,message:ai.reply,provider:ai.provider,model:ai.model,mode,guest:!req.user,workspace_connected:!!req.user})}catch(e){res.status(e.status||500).json({success:false,error:e.message||"Failed to generate response."})}});
app.post("/api/auth/signup",async(req,res)=>{const c=await pool.connect();try{const{username,email,phone,password,display_name}=req.body||{},ue=validateUsername(username),pe=validatePassword(password),ee=validateEmail(email);if(ue)return res.status(400).json({success:false,error:ue});if(pe)return res.status(400).json({success:false,error:pe});if(ee)return res.status(400).json({success:false,error:ee});const u=normalizeUsername(username),em=email?normalizeEmail(email):null,ph=phone?norm(phone):null,ex=await c.query(`SELECT user_id,username,email FROM users WHERE LOWER(username)=$1 OR($2::text IS NOT NULL AND LOWER(email)=$2)LIMIT 1`,[u,em]);if(ex.rows.length)return res.status(409).json({success:false,error:normalizeUsername(ex.rows[0].username)===u?"Username is already taken.":"Email is already registered."});const pw=hashPassword(password),user={user_id:makeId("usr"),username:norm(username),email:em,phone:ph,display_name:safeText(display_name,60)||norm(username),avatar:null,role:"user",password_hash:pw.hash,password_salt:pw.salt,created_at:now(),updated_at:now()};await c.query(`INSERT INTO users(user_id,username,email,phone,display_name,avatar,role,password_hash,password_salt,created_at,updated_at)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,Object.values(user));const s=await createSession(user.user_id,req);res.status(201).json({success:true,user:publicUser(user),session:{token:s.token,session_id:s.session_id}})}catch(e){console.error("Signup error:",e);res.status(500).json({success:false,error:"Signup failed: "+e.message})}finally{c.release()}});
app.post("/api/auth/login",async(req,res)=>{try{const{identifier,password}=req.body||{};if(!identifier||!password)return res.status(400).json({success:false,error:"Identifier and password are required."});const v=norm(identifier),r=await query(`SELECT * FROM users WHERE LOWER(username)=$1 OR LOWER(email)=$1 OR phone=$2 LIMIT 1`,[normalizeUsername(v),v]),u=r.rows[0];if(!u||!verifyPassword(password,u.password_hash,u.password_salt))return res.status(401).json({success:false,error:"Invalid login credentials."});const s=await createSession(u.user_id,req);res.json({success:true,user:publicUser(u),session:{token:s.token,session_id:s.session_id}})}catch(e){res.status(500).json({success:false,error:"Login failed: "+e.message})}});
app.get("/api/auth/me",authenticate,(req,res)=>res.json({success:true,user:publicUser(req.user),session:publicSession(req.session)}));
app.post("/api/auth/logout",authenticate,async(req,res)=>{try{await query(`DELETE FROM sessions WHERE session_id=$1 AND user_id=$2`,[req.session.session_id,req.user.user_id]);res.json({success:true,message:"Logged out successfully."})}catch(e){res.status(500).json({success:false,error:"Logout failed."})}});
app.get("/api/chats",authenticate,async(req,res)=>{try{const r=await query(`SELECT * FROM chats WHERE user_id=$1 ORDER BY updated_at DESC`,[req.user.user_id]);res.json({success:true,chats:r.rows.map(x=>({...x,messages:x.messages||[]}))})}catch(e){res.status(500).json({success:false,error:"Failed to load chats."})}});
app.post("/api/chats",authenticate,async(req,res)=>{try{const{mode="unified",provider="gemini",title="New Chat",messages=[],project_id=null}=req.body||{},c={chat_id:makeId("chat"),user_id:req.user.user_id,mode,provider,title:safeText(title,100)||"New Chat",messages:Array.isArray(messages)?messages.slice(-100):[],created_at:now(),updated_at:now()};if(!await columnExists("chats","project_id"))await query(`ALTER TABLE chats ADD COLUMN project_id TEXT REFERENCES projects(project_id) ON DELETE SET NULL`);c.project_id=project_id;await query(`INSERT INTO chats(chat_id,user_id,mode,provider,title,messages,created_at,updated_at,project_id)VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9)`,[c.chat_id,c.user_id,c.mode,c.provider,c.title,JSON.stringify(c.messages),c.created_at,c.updated_at,c.project_id]);res.status(201).json({success:true,chat:c})}catch(e){res.status(500).json({success:false,error:"Failed to create chat."})}});
async function columnExists(table,column){const r=await query(`SELECT 1 FROM information_schema.columns WHERE table_name=$1 AND column_name=$2`,[table,column]);return r.rows.length>0}
app.put("/api/chats/:id",authenticate,async(req,res)=>{try{const r=await query(`SELECT * FROM chats WHERE chat_id=$1 AND user_id=$2 LIMIT 1`,[req.params.id,req.user.user_id]);if(!r.rows.length)return res.status(404).json({success:false,error:"Chat not found."});const c=r.rows[0],{title,messages,mode,provider}=req.body||{};if(title)c.title=safeText(title,100);if(Array.isArray(messages))c.messages=messages.slice(-100);if(mode)c.mode=mode;if(provider)c.provider=provider;c.updated_at=now();await query(`UPDATE chats SET title=$1,messages=$2::jsonb,mode=$3,provider=$4,updated_at=$5 WHERE chat_id=$6 AND user_id=$7`,[c.title,JSON.stringify(c.messages||[]),c.mode,c.provider,c.updated_at,c.chat_id,req.user.user_id]);res.json({success:true,chat:c})}catch(e){res.status(500).json({success:false,error:"Failed to update chat."})}});
app.delete("/api/chats/:id",authenticate,async(req,res)=>{try{await query(`DELETE FROM chats WHERE chat_id=$1 AND user_id=$2`,[req.params.id,req.user.user_id]);res.json({success:true,message:"Chat deleted."})}catch(e){res.status(500).json({success:false,error:"Failed to delete chat."})}});
app.get("/api/memory",authenticate,async(req,res)=>{try{const r=await query(`SELECT * FROM memories WHERE user_id=$1 ORDER BY created_at ASC`,[req.user.user_id]);res.json({success:true,memories:r.rows})}catch(e){res.status(500).json({success:false,error:"Failed to load memory."})}});
app.post("/api/memory",authenticate,async(req,res)=>{try{const{content}=req.body||{};if(!norm(content))return res.status(400).json({success:false,error:"Content required."});const m={memory_id:makeId("mem"),user_id:req.user.user_id,content:safeText(content,1000),created_at:now()};await query(`INSERT INTO memories(memory_id,user_id,content,created_at)VALUES($1,$2,$3,$4)`,Object.values(m));res.status(201).json({success:true,memory:m})}catch(e){res.status(500).json({success:false,error:"Failed to save memory."})}});
app.delete("/api/memory/:id",authenticate,async(req,res)=>{try{await query(`DELETE FROM memories WHERE memory_id=$1 AND user_id=$2`,[req.params.id,req.user.user_id]);res.json({success:true,message:"Memory removed."})}catch(e){res.status(500).json({success:false,error:"Failed to remove memory."})}});
app.get("/api/projects",authenticate,async(req,res)=>{try{const r=await query(`SELECT * FROM projects WHERE user_id=$1 ORDER BY updated_at DESC`,[req.user.user_id]);res.json({success:true,projects:r.rows})}catch(e){res.status(500).json({success:false,error:"Failed to load projects."})}});
app.post("/api/projects",authenticate,async(req,res)=>{try{const{name,description=""}=req.body||{};if(!norm(name))return res.status(400).json({success:false,error:"Project name is required."});const p={project_id:makeId("proj"),user_id:req.user.user_id,name:safeText(name,80),description:safeText(description,500),created_at:now(),updated_at:now()};await query(`INSERT INTO projects(project_id,user_id,name,description,created_at,updated_at)VALUES($1,$2,$3,$4,$5,$6)`,Object.values(p));res.status(201).json({success:true,project:p})}catch(e){res.status(500).json({success:false,error:"Failed to create project."})}});
app.delete("/api/projects/:id",authenticate,async(req,res)=>{try{await query(`DELETE FROM projects WHERE project_id=$1 AND user_id=$2`,[req.params.id,req.user.user_id]);res.json({success:true,message:"Project removed."})}catch(e){res.status(500).json({success:false,error:"Failed to remove project."})}});
app.get("/api/tasks",authenticate,async(req,res)=>{try{const r=await query(`SELECT * FROM tasks WHERE user_id=$1 ORDER BY completed ASC,updated_at DESC`,[req.user.user_id]);res.json({success:true,tasks:r.rows})}catch(e){res.status(500).json({success:false,error:"Failed to load tasks."})}});
app.post("/api/tasks",authenticate,async(req,res)=>{try{const{title,project_id=null}=req.body||{};if(!norm(title))return res.status(400).json({success:false,error:"Task title is required."});if(project_id){const p=await query(`SELECT project_id FROM projects WHERE project_id=$1 AND user_id=$2`,[project_id,req.user.user_id]);if(!p.rows.length)return res.status(400).json({success:false,error:"Project not found."})}const t={task_id:makeId("task"),user_id:req.user.user_id,project_id,title:safeText(title,300),completed:false,created_at:now(),updated_at:now()};await query(`INSERT INTO tasks(task_id,user_id,project_id,title,completed,created_at,updated_at)VALUES($1,$2,$3,$4,$5,$6,$7)`,Object.values(t));res.status(201).json({success:true,task:t})}catch(e){res.status(500).json({success:false,error:"Failed to create task."})}});
app.put("/api/tasks/:id",authenticate,async(req,res)=>{try{const{title,completed,project_id}=req.body||{},r=await query(`UPDATE tasks SET title=COALESCE($1,title),completed=COALESCE($2,completed),project_id=COALESCE($3,project_id),updated_at=$4 WHERE task_id=$5 AND user_id=$6 RETURNING *`,[title?safeText(title,300):null,typeof completed==="boolean"?completed:null,project_id||null,now(),req.params.id,req.user.user_id]);if(!r.rows.length)return res.status(404).json({success:false,error:"Task not found."});res.json({success:true,task:r.rows[0]})}catch(e){res.status(500).json({success:false,error:"Failed to update task."})}});
app.delete("/api/tasks/:id",authenticate,async(req,res)=>{try{await query(`DELETE FROM tasks WHERE task_id=$1 AND user_id=$2`,[req.params.id,req.user.user_id]);res.json({success:true,message:"Task removed."})}catch(e){res.status(500).json({success:false,error:"Failed to remove task."})}});
app.get("/api/account/sessions",authenticate,async(req,res)=>{try{const r=await query(`SELECT session_id,user_id,device_name,created_at,last_seen FROM sessions WHERE user_id=$1 ORDER BY last_seen DESC`,[req.user.user_id]);res.json({success:true,sessions:r.rows.map(s=>({...publicSession(s),current:s.session_id===req.session.session_id}))})}catch(e){res.status(500).json({success:false,error:"Failed to load sessions."})}});
app.post("/api/account/change-password",authenticate,async(req,res)=>{try{const{current_password,new_password}=req.body||{};if(!verifyPassword(current_password,req.user.password_hash,req.user.password_salt))return res.status(401).json({success:false,error:"Current password is incorrect."});const er=validatePassword(new_password);if(er)return res.status(400).json({success:false,error:er});const h=hashPassword(new_password);await query(`UPDATE users SET password_hash=$1,password_salt=$2,updated_at=$3 WHERE user_id=$4`,[h.hash,h.salt,now(),req.user.user_id]);res.json({success:true,message:"Password changed successfully."})}catch(e){res.status(500).json({success:false,error:"Password change failed."})}});
async function startServer(){try{await initializeDatabase();if(!(await columnExists("chats","project_id")))await query(`ALTER TABLE chats ADD COLUMN project_id TEXT REFERENCES projects(project_id) ON DELETE SET NULL`);app.listen(PORT,()=>console.log(`Shiva 2.0 Backend running on port ${PORT}`))}catch(e){console.error("Startup failed:",e.message);process.exit(1)}}startServer();
