/*
  SHIVA 2.0 — PostgreSQL Backend
  Preserves:
  - Authentication
  - Secure scrypt password hashing
  - Sessions
  - Guest AI
  - Gemini + Groq Router
  - Common Shiva AI Identity
  - Chats
  - Memory
  - Projects
  - Account sessions
  - Change password
*/

const express = require("express");
const cors = require("cors");
const crypto = require("crypto");
const { Pool } = require("pg");

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json({ limit: "2mb" }));

if (!process.env.DATABASE_URL) console.warn("WARNING: DATABASE_URL is not configured.");
const pool = new Pool({connectionString: process.env.DATABASE_URL,ssl: process.env.DATABASE_URL ? { rejectUnauthorized: false } : undefined});
async function query(text, params = []) { return pool.query(text, params); }

async function initializeDatabase() {
  if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is not configured.");
  await query(`
    CREATE TABLE IF NOT EXISTS users (user_id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,email TEXT UNIQUE,phone TEXT,display_name TEXT,avatar TEXT,role TEXT NOT NULL DEFAULT 'user',password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
    CREATE TABLE IF NOT EXISTS sessions (session_id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,token TEXT NOT NULL UNIQUE,device_name TEXT,created_at TIMESTAMPTZ NOT NULL,last_seen TIMESTAMPTZ NOT NULL);
    CREATE TABLE IF NOT EXISTS chats (chat_id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,mode TEXT NOT NULL DEFAULT 'unified',provider TEXT NOT NULL DEFAULT 'gemini',title TEXT NOT NULL DEFAULT 'New Chat',messages JSONB NOT NULL DEFAULT '[]'::jsonb,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
    CREATE TABLE IF NOT EXISTS memories (memory_id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,content TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL);
    CREATE TABLE IF NOT EXISTS projects (project_id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
    CREATE TABLE IF NOT EXISTS reset_tokens (token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL);
    CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token);CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);CREATE INDEX IF NOT EXISTS idx_chats_user ON chats(user_id);CREATE INDEX IF NOT EXISTS idx_memories_user ON memories(user_id);CREATE INDEX IF NOT EXISTS idx_projects_user ON projects(user_id);
  `);console.log("PostgreSQL database initialized.");
}
function now(){return new Date().toISOString()}function makeId(prefix="id"){return `${prefix}_${crypto.randomBytes(16).toString("hex")}`}function normalizeUsername(username){return String(username||"").trim().toLowerCase()}function normalizeEmail(email){return String(email||"").trim().toLowerCase()}function normalizePhone(phone){return String(phone||"").trim()}function safeText(value,max=10000){return String(value||"").slice(0,max)}function hashPassword(password,salt=crypto.randomBytes(16).toString("hex")){const hash=crypto.scryptSync(password,salt,64).toString("hex");return{salt,hash}}function verifyPassword(password,storedHash,salt){try{const calculated=crypto.scryptSync(password,salt,64).toString("hex"),a=Buffer.from(calculated,"hex"),b=Buffer.from(storedHash,"hex");if(a.length!==b.length)return false;return crypto.timingSafeEqual(a,b)}catch{return false}}function generateToken(bytes=48){return crypto.randomBytes(bytes).toString("hex")}
function publicUser(user){if(!user)return null;return{user_id:user.user_id,username:user.username,email:user.email||null,phone:user.phone||null,display_name:user.display_name||user.username,avatar:user.avatar||null,role:user.role||"user",created_at:user.created_at,updated_at:user.updated_at}}
function publicSession(session){return{session_id:session.session_id,user_id:session.user_id,device_name:session.device_name||"Unknown device",created_at:session.created_at,last_seen:session.last_seen,current:false}}
function validateUsername(username){const value=String(username||"").trim();if(value.length<3||value.length>20)return"Username must be 3–20 characters.";if(!/^[A-Za-z0-9_@]+$/.test(value))return"Username can contain only letters, numbers, _ and @.";if(["admin","administrator","root","system","official","security"].includes(value.toLowerCase()))return"This username is reserved.";return null}
function validatePassword(password){const value=String(password||"");if(value.length<5||value.length>32)return"Password must be 5–32 characters.";return null}function validateEmail(email){if(!email)return null;const value=normalizeEmail(email);if(value.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))return"Invalid email address.";return null}
async function createSession(userId,req){const session={session_id:makeId("sess"),user_id:userId,token:generateToken(48),device_name:req.body?.device_name||req.headers["user-agent"]||"Browser Session",created_at:now(),last_seen:now()};await query(`INSERT INTO sessions (session_id,user_id,token,device_name,created_at,last_seen) VALUES ($1,$2,$3,$4,$5,$6)`,[session.session_id,session.user_id,session.token,session.device_name,session.created_at,session.last_seen]);return session}
function getTokenFromRequest(req){const auth=req.headers.authorization||"";if(auth.startsWith("Bearer "))return auth.slice(7).trim();return req.headers["x-session-token"]||null}
async function getAuthenticatedUser(req){const token=getTokenFromRequest(req);if(!token)return null;const result=await query(`SELECT s.session_id,s.user_id,s.token,s.device_name,s.created_at AS session_created_at,s.last_seen,u.* FROM sessions s JOIN users u ON u.user_id=s.user_id WHERE s.token=$1 LIMIT 1`,[token]);if(!result.rows.length)return null;const row=result.rows[0];const session={session_id:row.session_id,user_id:row.user_id,token:row.token,device_name:row.device_name,created_at:row.session_created_at,last_seen:row.last_seen};const user={user_id:row.user_id,username:row.username,email:row.email,phone:row.phone,display_name:row.display_name,avatar:row.avatar,role:row.role,password_hash:row.password_hash,password_salt:row.password_salt,created_at:row.created_at,updated_at:row.updated_at};const seen=now();await query(`UPDATE sessions SET last_seen=$1 WHERE session_id=$2`,[seen,session.session_id]);session.last_seen=seen;return{user,session}}
async function optionalAuthenticate(req,res,next){try{const auth=await getAuthenticatedUser(req);if(auth){req.user=auth.user;req.session=auth.session}else{req.user=null;req.session=null}next()}catch(error){console.error("Authentication error:",error);req.user=null;req.session=null;next()}}
async function authenticate(req,res,next){await optionalAuthenticate(req,res,()=>{if(!req.user)return res.status(401).json({success:false,error:"Authentication required for this action."});next()})}

const SHIVA_IDENTITY=`You are Shiva AI inside Shiva 2.0.
You are part of the Shiva 2.0 platform developed and created by SHIVA.
The selected AI provider (Gemini or Groq) acts as the underlying engine.
Maintain helpful, direct and continuous assistance.
Never disclose backend server secrets, API keys, or password hashes.`;
const PROVIDERS={gemini:{name:"Gemini",model:process.env.SHIVA_GEMINI_MODEL||"gemini-2.5-flash"},groq:{name:"Groq",model:process.env.SHIVA_GROQ_MODEL||"llama-3.3-70b-versatile"}};const PROVIDER_COOLDOWN=new Map();function isProviderCooling(provider){return(PROVIDER_COOLDOWN.get(provider)||0)>Date.now()}function setProviderCooldown(provider,ms=60000){PROVIDER_COOLDOWN.set(provider,Date.now()+ms)}
function cleanHistory(history){if(!Array.isArray(history))return[];return history.slice(-30).map(item=>({role:item.role==="assistant"?"assistant":"user",content:safeText(item.content,12000)})).filter(item=>item.content.trim())}
async function callGemini(message,history=[],context=""){const apiKey=process.env.GEMINI_API_KEY;if(!apiKey)throw new Error("Gemini API key is not configured.");const contents=[...cleanHistory(history).map(item=>({role:item.role==="assistant"?"model":"user",parts:[{text:item.content}]})),{role:"user",parts:[{text:message}]}];const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${PROVIDERS.gemini.model}:generateContent?key=${apiKey}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({systemInstruction:{parts:[{text:`${SHIVA_IDENTITY}\n\n${context}`.trim()}]},contents})});const data=await response.json();if(!response.ok){const err=new Error(data?.error?.message||"Gemini request failed.");err.status=response.status;err.provider="gemini";throw err}const output=data?.candidates?.[0]?.content?.parts?.[0]?.text||"";if(!output.trim())throw new Error("Gemini returned an empty response.");return output}
async function callGroq(message,history=[],context=""){const apiKey=process.env.GROQ_API_KEY;if(!apiKey)throw new Error("Groq API key is not configured.");const messages=[{role:"system",content:`${SHIVA_IDENTITY}\n\n${context}`.trim()},...cleanHistory(history),{role:"user",content:message}];const response=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${apiKey}`},body:JSON.stringify({model:PROVIDERS.groq.model,messages})});const data=await response.json();if(!response.ok){const err=new Error(data?.error?.message||"Groq request failed.");err.status=response.status;err.provider="groq";throw err}const output=data?.choices?.[0]?.message?.content||"";if(!output.trim())throw new Error("Groq returned an empty response.");return output}
async function routeToAI({provider,message,history,context}){const target=provider==="groq"?"groq":"gemini",order=target==="groq"?["groq","gemini"]:["gemini","groq"],failures=[];for(const p of order){if(isProviderCooling(p))continue;try{const reply=p==="groq"?await callGroq(message,history,context):await callGemini(message,history,context);return{reply,provider:p}}catch(e){if(e.status===429)setProviderCooldown(p,60000);failures.push({provider:p,error:e.message});console.error(`Provider error [${p}]:`,e.message)}}const err=new Error(failures.length?failures.map(f=>`${f.provider}: ${f.error}`).join(" | "):"No AI providers available.");err.status=503;throw err}

app.get("/api/status",async(req,res)=>{try{const dbCheck=await query("SELECT NOW() AS time");res.json({success:true,status:"online",database:"postgresql",database_time:dbCheck.rows[0].time,name:"Shiva 2.0 Backend",version:"2.0.0",providers:Object.keys(PROVIDERS)})}catch(error){res.status(503).json({success:false,status:"database_unavailable",error:error.message})}});
app.post("/api/message",optionalAuthenticate,async(req,res)=>{try{const{message,history=[],provider="gemini",mode="unified"}=req.body||{};if(!message||!String(message).trim())return res.status(400).json({success:false,error:"Message cannot be empty."});let context="";if(req.user){const memories=await query(`SELECT content FROM memories WHERE user_id=$1 ORDER BY created_at DESC LIMIT 8`,[req.user.user_id]);if(memories.rows.length)context+="\nUser Memory:\n"+memories.rows.reverse().map(m=>`- ${m.content}`).join("\n")}const aiResult=await routeToAI({provider,message:String(message).trim(),history,context});res.json({success:true,reply:aiResult.reply,provider:aiResult.provider,mode,guest:!req.user})}catch(error){res.status(error.status||500).json({success:false,error:error.message||"Failed to generate response."})}});

app.post("/api/auth/signup",async(req,res)=>{const client=await pool.connect();try{const{username,email,phone,password,display_name}=req.body||{},uErr=validateUsername(username),pErr=validatePassword(password),eErr=validateEmail(email);if(uErr)return res.status(400).json({success:false,error:uErr});if(pErr)return res.status(400).json({success:false,error:pErr});if(eErr)return res.status(400).json({success:false,error:eErr});const normUser=normalizeUsername(username),normEmail=email?normalizeEmail(email):null,normPhone=phone?normalizePhone(phone):null;const existing=await client.query(`SELECT user_id,username,email FROM users WHERE LOWER(username)=$1 OR ($2::text IS NOT NULL AND LOWER(email)=$2) LIMIT 1`,[normUser,normEmail]);if(existing.rows.length){const row=existing.rows[0];if(normalizeUsername(row.username)===normUser)return res.status(409).json({success:false,error:"Username is already taken."});return res.status(409).json({success:false,error:"Email is already registered."})}const pwd=hashPassword(password),user={user_id:makeId("usr"),username:String(username).trim(),email:normEmail,phone:normPhone,display_name:safeText(display_name,60)||String(username).trim(),avatar:null,role:"user",password_hash:pwd.hash,password_salt:pwd.salt,created_at:now(),updated_at:now()};await client.query(`INSERT INTO users (user_id,username,email,phone,display_name,avatar,role,password_hash,password_salt,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[user.user_id,user.username,user.email,user.phone,user.display_name,user.avatar,user.role,user.password_hash,user.password_salt,user.created_at,user.updated_at]);const session=await createSession(user.user_id,req);res.status(201).json({success:true,user:publicUser(user),session:{token:session.token,session_id:session.session_id}})}catch(error){console.error("Signup error:",error);res.status(500).json({success:false,error:"Signup failed: "+error.message})}finally{client.release()}});
app.post("/api/auth/login",async(req,res)=>{try{const{identifier,password}=req.body||{};if(!identifier||!password)return res.status(400).json({success:false,error:"Identifier and password are required."});const val=String(identifier).trim(),result=await query(`SELECT * FROM users WHERE LOWER(username)=$1 OR LOWER(email)=$1 OR phone=$2 LIMIT 1`,[normalizeUsername(val),normalizePhone(val)]),user=result.rows[0];if(!user||!verifyPassword(password,user.password_hash,user.password_salt))return res.status(401).json({success:false,error:"Invalid login credentials."});const session=await createSession(user.user_id,req);res.json({success:true,user:publicUser(user),session:{token:session.token,session_id:session.session_id}})}catch(error){console.error("Login error:",error);res.status(500).json({success:false,error:"Login failed: "+error.message})}});
app.get("/api/auth/me",authenticate,(req,res)=>res.json({success:true,user:publicUser(req.user),session:publicSession(req.session)}));
app.post("/api/auth/logout",authenticate,async(req,res)=>{try{await query(`DELETE FROM sessions WHERE session_id=$1 AND user_id=$2`,[req.session.session_id,req.user.user_id]);res.json({success:true,message:"Logged out successfully."})}catch(error){res.status(500).json({success:false,error:"Logout failed."})}});

app.get("/api/chats",authenticate,async(req,res)=>{try{const result=await query(`SELECT * FROM chats WHERE user_id=$1 ORDER BY updated_at DESC`,[req.user.user_id]);res.json({success:true,chats:result.rows.map(row=>({...row,messages:row.messages||[]}))})}catch(error){res.status(500).json({success:false,error:"Failed to load chats."})}});
app.post("/api/chats",authenticate,async(req,res)=>{try{const{mode="unified",provider="gemini",title="New Chat",messages=[]}=req.body||{},chat={chat_id:makeId("chat"),user_id:req.user.user_id,mode,provider,title:safeText(title,100)||"New Chat",messages:Array.isArray(messages)?messages.slice(-100):[],created_at:now(),updated_at:now()};await query(`INSERT INTO chats (chat_id,user_id,mode,provider,title,messages,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6::jsonb,$7,$8)`,[chat.chat_id,chat.user_id,chat.mode,chat.provider,chat.title,JSON.stringify(chat.messages),chat.created_at,chat.updated_at]);res.status(201).json({success:true,chat})}catch(error){res.status(500).json({success:false,error:"Failed to create chat."})}});
app.put("/api/chats/:id",authenticate,async(req,res)=>{try{const current=await query(`SELECT * FROM chats WHERE chat_id=$1 AND user_id=$2 LIMIT 1`,[req.params.id,req.user.user_id]);if(!current.rows.length)return res.status(404).json({success:false,error:"Chat not found."});const chat=current.rows[0],{title,messages,mode,provider}=req.body||{};if(title)chat.title=safeText(title,100);if(Array.isArray(messages))chat.messages=messages.slice(-100);if(mode)chat.mode=mode;if(provider)chat.provider=provider;chat.updated_at=now();await query(`UPDATE chats SET title=$1,messages=$2::jsonb,mode=$3,provider=$4,updated_at=$5 WHERE chat_id=$6 AND user_id=$7`,[chat.title,JSON.stringify(chat.messages||[]),chat.mode,chat.provider,chat.updated_at,chat.chat_id,req.user.user_id]);res.json({success:true,chat})}catch(error){res.status(500).json({success:false,error:"Failed to update chat."})}});
app.delete("/api/chats/:id",authenticate,async(req,res)=>{try{await query(`DELETE FROM chats WHERE chat_id=$1 AND user_id=$2`,[req.params.id,req.user.user_id]);res.json({success:true,message:"Chat deleted."})}catch(error){res.status(500).json({success:false,error:"Failed to delete chat."})}});

app.get("/api/memory",authenticate,async(req,res)=>{try{const result=await query(`SELECT * FROM memories WHERE user_id=$1 ORDER BY created_at ASC`,[req.user.user_id]);res.json({success:true,memories:result.rows})}catch(error){res.status(500).json({success:false,error:"Failed to load memory."})}});
app.post("/api/memory",authenticate,async(req,res)=>{try{const{content}=req.body||{};if(!content||!String(content).trim())return res.status(400).json({success:false,error:"Content required."});const memory={memory_id:makeId("mem"),user_id:req.user.user_id,content:safeText(content,1000),created_at:now()};await query(`INSERT INTO memories (memory_id,user_id,content,created_at) VALUES ($1,$2,$3,$4)`,[memory.memory_id,memory.user_id,memory.content,memory.created_at]);res.status(201).json({success:true,memory})}catch(error){res.status(500).json({success:false,error:"Failed to save memory."})}});
app.delete("/api/memory/:id",authenticate,async(req,res)=>{try{await query(`DELETE FROM memories WHERE memory_id=$1 AND user_id=$2`,[req.params.id,req.user.user_id]);res.json({success:true,message:"Memory removed."})}catch(error){res.status(500).json({success:false,error:"Failed to remove memory."})}});

app.get("/api/projects",authenticate,async(req,res)=>{try{const result=await query(`SELECT * FROM projects WHERE user_id=$1 ORDER BY updated_at DESC`,[req.user.user_id]);res.json({success:true,projects:result.rows})}catch(error){res.status(500).json({success:false,error:"Failed to load projects."})}});
app.post("/api/projects",authenticate,async(req,res)=>{try{const{name,description=""}=req.body||{};if(!name||!String(name).trim())return res.status(400).json({success:false,error:"Project name is required."});const project={project_id:makeId("proj"),user_id:req.user.user_id,name:safeText(name,80),description:safeText(description,500),created_at:now(),updated_at:now()};await query(`INSERT INTO projects (project_id,user_id,name,description,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6)`,[project.project_id,project.user_id,project.name,project.description,project.created_at,project.updated_at]);res.status(201).json({success:true,project})}catch(error){res.status(500).json({success:false,error:"Failed to create project."})}});
app.delete("/api/projects/:id",authenticate,async(req,res)=>{try{await query(`DELETE FROM projects WHERE project_id=$1 AND user_id=$2`,[req.params.id,req.user.user_id]);res.json({success:true,message:"Project removed."})}catch(error){res.status(500).json({success:false,error:"Failed to remove project."})}});

app.get("/api/account/sessions",authenticate,async(req,res)=>{try{const result=await query(`SELECT session_id,user_id,device_name,created_at,last_seen FROM sessions WHERE user_id=$1 ORDER BY last_seen DESC`,[req.user.user_id]);const sessions=result.rows.map(session=>({...publicSession(session),current:session.session_id===req.session.session_id}));res.json({success:true,sessions})}catch(error){res.status(500).json({success:false,error:"Failed to load sessions."})}});
app.post("/api/account/change-password",authenticate,async(req,res)=>{try{const{current_password,new_password}=req.body||{};if(!verifyPassword(current_password,req.user.password_hash,req.user.password_salt))return res.status(401).json({success:false,error:"Current password is incorrect."});const pErr=validatePassword(new_password);if(pErr)return res.status(400).json({success:false,error:pErr});const hashed=hashPassword(new_password),updatedAt=now();await query(`UPDATE users SET password_hash=$1,password_salt=$2,updated_at=$3 WHERE user_id=$4`,[hashed.hash,hashed.salt,updatedAt,req.user.user_id]);res.json({success:true,message:"Password changed successfully."})}catch(error){res.status(500).json({success:false,error:"Password change failed."})}});

async function startServer(){try{await initializeDatabase();app.listen(PORT,()=>console.log(`Shiva 2.0 Backend running on port ${PORT}`))}catch(error){console.error("Startup failed:",error.message);process.exit(1)}}startServer();
